CREATE SEQUENCE hilo_computer_image_seq START with 1 INCREMENT BY 5;

create table computer_image (
    main integer not null,
    image_id bigint not null,
    image oid not null,
    computer_id varchar(255),
    primary key (image_id)
);

create table laptop (
    computer_id varchar(255) not null,
    relevant integer not null,
    bluetooth boolean,
    bluetooth_version varchar(255),
    brand varchar(255) not null,
    camera boolean,
    camera_resolution integer,
    case_color varchar(255),
    case_lighting boolean,
    case_material varchar(255),
    discrete_coprocessor boolean,
    display_brightness integer,
    display_characteristics varchar(255),
    display_technology varchar(255),
    dynamic_number integer,
    energy_capacity integer,
    graphics_capacity integer,
    graphics_characteristics varchar(255),
    graphics_model varchar(255),
    hdmi boolean,
    hdmi_version varchar(255),
    height double precision,
    jack boolean,
    jack_number integer,
    keyboard_lighting boolean,
    keyboard_lighting_color varchar(255),
    lan boolean, lan_version varchar(255),
    length double precision, lid_color varchar(255),
    lid_material varchar(255),
    microphone boolean,
    microphone_number integer,
    model varchar(255) not null,
    nfc boolean,
    numpad boolean,
    odd boolean,
    os boolean,
    os_type varchar(255),
    processor varchar(255),
    processor_clock_frequency integer,
    processor_max_clock_frequency integer,
    processor_model varchar(255),
    processor_number integer,
    processor_platform varchar(255),
    processor_tdp integer,
    processor_thread_number integer,
    ram integer,
    ram_clock_frequency integer,
    ram_free_slots integer,
    ram_max integer,
    ram_max_slots integer,
    ram_type varchar(255),
    refresh_rate integer,
    release_year varchar(255),
    screen_cover varchar(255),
    screen_resolution varchar(255),
    screen_size double precision,
    sensor_display boolean,
    serial_id varchar(255) not null unique,
    storage_capacity integer,
    storage_interface_type varchar(255),
    storage_slots integer,
    storage_type varchar(255),
    sub_model varchar(255),
    touchpad boolean,
    type integer,
    typec boolean,
    typeccharge boolean,
    typecnumber integer,
    usb boolean,
    usb_number integer,
    vga boolean,
    vga_version varchar(255),
    weight double precision,
    width double precision,
    wifi boolean,
    wifi_version varchar(255),
    work_time time,
    primary key (computer_id)
);

alter table laptop add constraint UK_8dt9m5vd3bx5ee40qiie4kqe7 unique (serial_id);

alter table computer_image add constraint FK9qq2c526ppotj6k1hf5727hx4 foreign key (computer_id) references laptop;



