--
-- Name: mobile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mobile (
    mobile_id character varying(255) NOT NULL,
    battery integer,
    brand character varying(255) NOT NULL,
    camera_resolution character varying(255),
    chipset_model character varying(255),
    color character varying(255),
    display_resolution character varying(255),
    display_technology character varying(255),
    model character varying(255),
    os character varying(255),
    ram integer,
    release_year character varying(255),
    screen_size character varying(255),
    sim_card_slot character varying(255),
    storage_capacity integer
);


ALTER TABLE public.mobile OWNER TO postgres;

--
-- Name: mobile_full; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mobile_full (
    audio_output boolean,
    audio_output_version character varying(255),
    automatic_focus boolean,
    battery_type character varying(255),
    beidou boolean,
    bluetooth boolean,
    bluetooth_version character varying(255),
    built_in_flash boolean,
    charge_time character varying(255),
    connection character varying(255),
    cores_number integer,
    edge boolean,
    five_g boolean,
    front_camera boolean,
    front_camera_aperture character varying(255),
    front_camera_resolution character varying(255),
    glonass boolean,
    gps boolean,
    height double precision,
    housing_material character varying(255),
    hspa boolean,
    hspa_plus boolean,
    length double precision,
    lte boolean,
    main_camera boolean,
    main_camera_aperture character varying(255),
    main_cameras_number integer,
    nfc boolean,
    optical_stabilization boolean,
    os_version character varying(255),
    processor_clock_frequency integer,
    sim_format character varying(255),
    technical_process integer,
    type character varying(255),
    weight double precision,
    width double precision,
    wifi boolean,
    wifi_version character varying(255),
    mobile_id character varying(255) NOT NULL
);


ALTER TABLE public.mobile_full OWNER TO postgres;

--
-- Name: mobile_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mobile_image (
    main integer NOT NULL,
    image_id bigint NOT NULL,
    image oid NOT NULL,
    mobile_id character varying(255) NOT NULL
);


ALTER TABLE public.mobile_image OWNER TO postgres;

--
-- Name: mobile_image_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mobile_image ALTER COLUMN image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mobile_image_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.offers (
    mobile_id character varying(255) NOT NULL,
    price double precision,
    shop_id bigint NOT NULL
);


ALTER TABLE public.offers OWNER TO postgres;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    order_id bigint NOT NULL,
    mobile_id character varying(255) NOT NULL,
    price double precision NOT NULL,
    registered_date date,
    shop_id bigint,
    task_id bigint NOT NULL,
    count integer NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop (
    shop_id bigint NOT NULL,
    description character varying(500),
    name character varying(255) NOT NULL,
    logo_id bigint
);


ALTER TABLE public.shop OWNER TO postgres;

--
-- Name: shop_logo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_logo (
    logo_id bigint NOT NULL,
    logo oid
);


ALTER TABLE public.shop_logo OWNER TO postgres;

--
-- Name: shop_logo_logo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop_logo ALTER COLUMN logo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_logo_logo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_shop_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop ALTER COLUMN shop_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_shop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_working_hours_mapping; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_working_hours_mapping (
    shop_id bigint NOT NULL,
    working_hours_id bigint NOT NULL,
    working_hours_map_key character varying(255) NOT NULL
);


ALTER TABLE public.shop_working_hours_mapping OWNER TO postgres;

--
-- Name: shops_payment_methods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shops_payment_methods (
    shop_id bigint NOT NULL,
    payment_method character varying(255)
);


ALTER TABLE public.shops_payment_methods OWNER TO postgres;

--
-- Name: task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task (
    task_id bigint NOT NULL,
    building character varying(255),
    city character varying(255) NOT NULL,
    comment character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    flat integer,
    floor integer,
    last_name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    porch integer,
    state integer,
    street character varying(255)
);


ALTER TABLE public.task OWNER TO postgres;

--
-- Name: task_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: working_hours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.working_hours (
    id bigint NOT NULL,
    close time without time zone,
    open time without time zone
);


ALTER TABLE public.working_hours OWNER TO postgres;

--
-- Name: working_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.working_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.working_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: mobile_full mobile_dto_full_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobile_full
    ADD CONSTRAINT mobile_dto_full_pkey PRIMARY KEY (mobile_id);


--
-- Name: mobile mobile_dto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobile
    ADD CONSTRAINT mobile_dto_pkey PRIMARY KEY (mobile_id);


--
-- Name: mobile_image mobile_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobile_image
    ADD CONSTRAINT mobile_image_pkey PRIMARY KEY (image_id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (mobile_id, shop_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: shop_logo shop_logo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_logo
    ADD CONSTRAINT shop_logo_pkey PRIMARY KEY (logo_id);


--
-- Name: shop shop_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop
    ADD CONSTRAINT shop_pkey PRIMARY KEY (shop_id);


--
-- Name: shop_working_hours_mapping shop_working_hours_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_working_hours_mapping
    ADD CONSTRAINT shop_working_hours_mapping_pkey PRIMARY KEY (shop_id, working_hours_map_key);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (task_id);


--
-- Name: shop_working_hours_mapping uk_rmov1khdmgnuvamqu58csdaep; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_working_hours_mapping
    ADD CONSTRAINT uk_rmov1khdmgnuvamqu58csdaep UNIQUE (working_hours_id);


--
-- Name: working_hours working_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_hours
    ADD CONSTRAINT working_hours_pkey PRIMARY KEY (id);

--
-- Name: offers fk3542455002n21db0je3g4u2ax; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk3542455002n21db0je3g4u2ax FOREIGN KEY (mobile_id) REFERENCES public.mobile_full(mobile_id);


--
-- Name: mobile_image fk3exdlsomyedw504hmtyet41po; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobile_image
    ADD CONSTRAINT fk3exdlsomyedw504hmtyet41po FOREIGN KEY (mobile_id) REFERENCES public.mobile(mobile_id);


--
-- Name: mobile_full fk3iqfix6vb0ylymxvt8vq7jqm8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mobile_full
    ADD CONSTRAINT fk3iqfix6vb0ylymxvt8vq7jqm8 FOREIGN KEY (mobile_id) REFERENCES public.mobile(mobile_id);


--
-- Name: shop_working_hours_mapping fk3mvqc76ls0b7ijumkadnicp6g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_working_hours_mapping
    ADD CONSTRAINT fk3mvqc76ls0b7ijumkadnicp6g FOREIGN KEY (shop_id) REFERENCES public.shop(shop_id);


--
-- Name: offers fk97ipf93d6tpovfj3jht8jjouo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk97ipf93d6tpovfj3jht8jjouo FOREIGN KEY (mobile_id) REFERENCES public.mobile(mobile_id);


--
-- Name: shop fkc15r3127pippr2qp01l346nm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop
    ADD CONSTRAINT fkc15r3127pippr2qp01l346nm FOREIGN KEY (logo_id) REFERENCES public.shop_logo(logo_id);


--
-- Name: orders fkighmnv5so1ixas1ujliln5x2v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkighmnv5so1ixas1ujliln5x2v FOREIGN KEY (task_id) REFERENCES public.task(task_id) ON DELETE CASCADE;


--
-- Name: shops_payment_methods fkktmduosnywvau8f8keiym3do6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shops_payment_methods
    ADD CONSTRAINT fkktmduosnywvau8f8keiym3do6 FOREIGN KEY (shop_id) REFERENCES public.shop(shop_id);


--
-- Name: offers fko9psbvu6qiy4lt5phx0jkn8pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fko9psbvu6qiy4lt5phx0jkn8pr FOREIGN KEY (shop_id) REFERENCES public.shop(shop_id);


--
-- Name: orders fkqqi25r9aqjq5aupcwtl5xye6y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkqqi25r9aqjq5aupcwtl5xye6y FOREIGN KEY (mobile_id) REFERENCES public.mobile(mobile_id);


--
-- Name: shop_working_hours_mapping fkqyu1fr6bgnsqlmr7ggfwgq4jg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_working_hours_mapping
    ADD CONSTRAINT fkqyu1fr6bgnsqlmr7ggfwgq4jg FOREIGN KEY (working_hours_id) REFERENCES public.working_hours(id);